sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t thejoud1997/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thejoud1997/docker-react npm run test
